name: agri_delivery_app
description: A Flutter app for agri product delivery system

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Add your other packages here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
